# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-03 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytomanyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='person',
            field=models.ManyToManyField(to='manytomanyapp.Person'),
        ),
    ]
