# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-03 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onetooneapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='country',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onetooneapp.Country'),
        ),
    ]
