# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-03 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytooneapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
    ]
