# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-03 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytooneapp', '0003_auto_20181003_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(4), to='manytooneapp.Author'),
        ),
    ]
