# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-03 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manytooneapp', '0004_auto_20181003_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manytooneapp.Author'),
        ),
    ]
